# Setup
title:               'Salmonid Ecology Group'
tagline:             'University of Gothenburg'
description:         'In SEG we study dispersal patterns and ecology in salmonids.'
url:                 'https://benediau.github.io'
baseurl:             '/seg-gbg'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
